[groups.'System.c4g']
parts = [
    'v360',
]

[groups.'Graphics.c4g']
parts = [
    'v360',
]

[groups.content]
parts = [
    'https://update.clonkspot.org/lc/lc_49110.zip',
]

[groups.content.'Fantasy.c4d']

[groups.content.'Fantasy.c4f']

[groups.content.'FarWorlds.c4d']

[groups.content.'FarWorlds.c4f']

[groups.content.'Hazard.c4d']

[groups.content.'Hazard.c4f']

[groups.content.'Knights.c4d']

[groups.content.'Knights.c4f']

[groups.content.'Material.c4g']

[groups.content.'Melees.c4f']

[groups.content.'Missions.c4f']

[groups.content.'Music.c4g']

[groups.content.'Objects.c4d']

[groups.content.'Races.c4f']

[groups.content.'Sound.c4g']

[groups.content.'Tutorial.c4f']

[groups.content.'Western.c4d']

[groups.content.'Western.c4f']

[groups.content.'Worlds.c4f']

[matrix.windows]
runner = 'windows-latest'

[[matrix.windows.config]]
arch = 'x86'
platform-suffix = 'win32'
itch-manifest = 'win32'

[[matrix.windows.config]]
arch = 'x64'
platform-suffix = 'win64'
itch-manifest = 'win64'
vs_arch = 'amd64'
include-groups = true
publish-groups = true

[[matrix.windows.config]]
name = 'debugrec'
arch = 'x86'
platform-suffix = 'win32'
debugrec = true

[matrix.linux]
runner = 'ubuntu-22.04'

[[matrix.linux.config]]
arch = 'x64'
platform-suffix = 'linux64'
itch-manifest = 'linux'

[[matrix.linux.config]]
name = 'debugrec'
arch = 'x64'
platform-suffix = 'linux64'
debugrec = true

[matrix.mac]
runner = 'macos-13'

[[matrix.mac.config]]
arch = 'x64'
platform-suffix = 'mac'
itch-manifest = 'mac'
